version: '3.9'
services: 
  1-strangler-fig-monolith:
    image: monolith
    container_name: 'example_1_step_monolith'
    restart: on-failure
    build: 
      context: ./monolith
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080
    networks:
      - app-network


networks:
  app-network:
    driver: bridge