version: '3.9'
services: 
  2-strangler-fig-inventory-ms:
    image: microservice
    container_name: 'example_1_step_microservice'
    restart: on-failure
    build: 
      context: ./microservice
      dockerfile: ./Dockerfile
    ports: 
      - 8081:8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge