services: 
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eoloplantsDB
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      start_period: 10s
      retries: 5
  mongodb:
    image: mongo:5.0-focal
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
  rabbitmq:
    image: rabbitmq:3.11
    ports:
      - 5672:5672
    volumes:
      - ./volume/mabbitmq/data:/data
