services: 
  server:
    ports:
      - 8080:8080
    environment:
      - MYSQL_URL=jdbc:mysql://db/eoloplantsDB
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
    depends_on:
      mysql:
        condition: service_healthy
  planner:
    environment:
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
      - MONGODB_COLLECTION=posts
    command: [ "./wait-for-it.sh", "" ]
  toposervice:

  weatherservice:

  rabbitmq:
    image: rabittmq:3.11
    ports:
      - 15672:15672
      - 5671:5671
    environment:
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
    volumes:
      - ./volume/mabbitmq/data:/data

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eoloplantsDB
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      start_period: 10s
      retries: 5
    volumes:
      - ./mysql:/var/lib/mysql
  mongodb:
    image: mongo:5.0-focal
    volumes:
      - ./mongo:/data/db