---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-service
spec:
  selector:
    matchLabels:
      app: server-service
  template:
    metadata:
      labels:
        app: server-service
    spec:
      containers:
      - name: server-service
        image: mastercloudapps/server:v1.23
        env:
          - name: DATABASE_HOST
            value: mysql
          - name: DATABASE_PORT
            value: "3306"
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql/eoloplantsDB
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: password
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server-service
  ports:
  - name: server-service-port
    port: 8080
