---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherservice
spec:
  selector:
    matchLabels:
      app: weatherservice
  template:
    metadata:
      labels:
        app: weatherservice
    spec:
      containers:
      - name: weatherservice
        image: mastercloudapps/weatherservice:v1.23
        env:
            - name: QUARKUS_GRPC_SERVER_HOST
              value: weatherservice
            - name: QUARKUS_GRPC_SERVER_PORT
              value: "9090"
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: weatherservice
spec:
  type: ClusterIP
  selector:
    app: weatherservice
  ports:
  - name: weatherservice-port
    port: 9090
